# Generated by Django 4.1.3 on 2022-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrackapp', '0004_dailytrack_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytrack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
